
<div class="footer-container col-12 d-flex flex-wrap justify-content-center pt-5">
    <div class="col-12 col-lg-5 px-3">
        <div class="col-12 px-0 pb-5 d-flex flex-wrap justify-content-center justify-content-md-start">
            <h5 class="col-12 text-center text-md-start pb-2">Contact</h5>
            <p class="col-12 text-center text-md-start pb-2"><span><i class="fa fa-envelope me-2"></i></span> <a class="text-white" href="mailto:deune@gravitysplash.com">deune@gravitysplash.com</a></p>
            <p class="col-12 text-center text-md-start pb-2"><span><i class="fa fa-envelope me-2"></i></span> <a class="text-white" href="mailto:dwayne@gravitysplash.com">dwayne@gravitysplash.com</a></p>
        </div>
    </div>
    <div class="col-12 col-lg-2 px-3">
        <div class="col-12 px-0 pb-5 d-flex flex-wrap justify-content-center justify-content-md-start">
            <h5 class="col-12 text-center text-md-start pb-2">Quick links</h5>
            <p class="col-12 text-center text-md-start pb-2"><a class="text-white"  href="pricing.php">Prices</a></p>
            <p class="col-12 text-center text-md-start pb-2"><a class="text-white"  href="portfolio.php">Portfolio</a></p>
            <p class="col-12 text-center text-md-start pb-2"><a class="text-white"  href="contact.php">Contact</a></p>
        </div>
    </div>
    <div class="col-12 col-lg-2 px-3">
        <div class="col-12 px-0 pb-5 d-flex flex-wrap justify-content-center justify-content-md-start">
            <h5 class="col-12 text-center text-md-start pb-2">Useful links</h5>
            <p class="col-12 text-center text-md-start pb-2"><a class="text-white" target="_blank" ><span><i class="fa fa-external-link-alt me-2"></i></span>Photography</a></p>
            <p class="col-12 text-center text-md-start pb-2"><a class="text-white" target="_blank"  ><span><i class="fa fa-external-link-alt me-2"></i></span>Printing</a></p>
        </div>
    </div>
</div>
<div id="main-navigation" class="col-12 bg-white">
    <div class="container-fluid py-2">
        <p class="col-12 text-center text-md-start mb-0 text-dark"><small>©Copyright 2023 GravitySplash. All Rights Reserved.</small></p>
    </div>
</div>
