
<div class="footer-container col-12 d-flex flex-wrap justify-content-center pt-5">
    <div class="col-12 col-lg-3 px-0 ">
        <div class="col-12 px-0">
            <h5>Contact</h5>
            <p>Email <a>deune@test.com</a></p>
            <p>Phone <a>061 277 1994</a></p>
        </div>
    </div>
    <div class="col-12 col-lg-3  px-0 ">
        <div class="col-12 px-0">
            <h5>Quick links</h5>
            <p><a>Prices</a></p>
            <p><a>Portfolio</a></p>
            <p><a>Contact</a></p>
        </div>
    </div>
    <div class="col-12 col-lg-3  px-0 ">
        <div class="col-12 px-0">
            <h5>Quick links</h5>
            <p><a>Prices</a></p>
            <p><a>Portfolio</a></p>
            <p><a>Contact</a></p>
        </div>
    </div>
</div>
<div id="main-navigation" class="col-12 bg-white">
    <div class="container-fluid py-2">
        <p class="col-12 text-center mb-0 text-dark"><small>©Copyright 2023 Something. All Rights Reserved.</small></p>
    </div>
</div>
