<nav id="main-navigation" class="col-12 navbar navbar-expand-lg py-3 position-fixed blurry">
    <div class="col-12 col-md-11 mx-auto d-flex justify-content-between px-3">
        <a class="navbar-brand" href="#"><img src="images/logo.png" /></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"><i class="fas fa-bars"></i></span>
        </button>
        <div class="collapse navbar-collapse d-lg-flex justify-content-end col-12 col-md-8 px-3" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link px-1 px-md-4 active" aria-current="page" href="index.php">Home</a>
                <a class="nav-link px-1 px-md-4" href="portfolio.php">Portfolio</a>
                <a class="nav-link px-1 px-md-4" href="pricing.php">Pricing</a>
                <a class="nav-link px-1 px-md-4" href="contact.php">Contact</a>
            </div>
        </div>
    </div>
</nav>
<div class="menu-break"></div>
