<nav id="main-navigation" class="col-12 navbar navbar-expand-lg py-3 position-fixed blurry">
    <div class="col-12 col-lg-11 mx-auto d-flex">
        <a class="navbar-brand" href="#"><img src="images/logo.png" /></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse ms-0 ms-md-5 col-12 col-md-8" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="index.php">Home</a>
                <a class="nav-link" href="portfolio.php">Portfolio</a>
                <a class="nav-link" href="pricing.php">Pricing</a>
                <a class="nav-link" href="contact.php">Contact</a>
            </div>
        </div>
    </div>
</nav>
<div class="menu-break"></div>
